#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /tasks
  controller: App\Controller\TaskController::index
  methods: [GET, POST]
  schemes: [HTTPS]
  host: tarefas.test

show:
  path: /tasks/show/{id}
  controller: App\Controller\TaskController::show
