#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /tasks
  controller: App\Controller\TaskController::index

show:
  path: /tasks/{id<\d+>}
  controller: App\Controller\TaskController::show
