#index:
#    path: /
#    controller: App\Controller\DefaultController::index

tasks_index:
  path: /tasks
  controller: App\Controller\TaskController::index
  methods: [GET, POST]
  schemes: [HTTPS]
  host: tarefas.test

tasks_show:
  path: /tasks/show/{id}
  controller: App\Controller\TaskController::show
  condition:  "context.getMethod() in ['GET'] and request.headers.get('User-Agent') matches '/Chrome/i'"

tasks_create:
  path: /tasks/create
  controller: App\Controller\TaskController::create
  